### ISSUE TITLE
Failed to read GEDCOM file (Webtrees 2.0.19)

### ISSUE THREAD

**Issue by arsaboo** [PeWu/topola-webtrees#13]
I am trying to use Topola with Webtrees (2.0.19) and have added the module in the `modules_v4` folder with the other modules. 

![image](https://user-images.githubusercontent.com/18319734/158467210-33235c3c-bc1f-46ea-8a85-ab2cd692c886.png)

However, when I try to use Topolo viewer, I get the following error. 

![image](https://user-images.githubusercontent.com/18319734/158466973-3ec560ac-947a-4614-9b70-bde6e16dad15.png)

**Comment by tasker25** [comment]
This is corrected in latest version.
